require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ShoppeDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'FullStory', :http => 'https://ios-releases.fullstory.com/fullstory-1.8.2.tar.gz'
  
  target 'ShoppeDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ShoppeDemo-tvOS' do
  # Pods for ShoppeDemo-tvOS

  target 'ShoppeDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
